# Generated by Django 4.0.3 on 2022-03-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='phone_number',
            field=models.PositiveIntegerField(error_messages={'null': 'This field cannot be null'}),
        ),
    ]
