# Generated by Django 4.0.3 on 2022-03-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_alter_testmodel_options_testmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmodel',
            options={},
        ),
    ]
