# Generated by Django 3.2.5 on 2022-03-27 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_alter_testmodel_options_modelx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodel',
            old_name='is_live',
            new_name='is_alive',
        ),
    ]
