# Generated by Django 3.2.5 on 2022-05-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmain',
            name='date',
            field=models.DateField(auto_created=True),
        ),
    ]
